# Generated by Django 2.1.5 on 2019-01-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog_event',
            name='image',
            field=models.ImageField(blank=True, upload_to='events/'),
        ),
    ]
